version: '3'
services:
  api:
    restart: always
    build: ./paibc5-back/
    ports:
      - 3005:3005
  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pa5IBC
      POSTGRES_USER: koko
    ports:
      - 5432:5432
  pa-front:
    stdin_open: true
    build: ./paibc5-front/
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app